export const PREFIX = "@@dietPlan/";

export const GET_FOOD_PATTERN_INIT = `${PREFIX}GET_FOOD_PATTERN_INIT`;
export const GET_FOOD_PATTERN_SUCCESS = `${PREFIX}GET_FOOD_PATTERN_SUCCESS`;
export const GET_FOOD_PATTERN_FAILURE = `${PREFIX}GET_FOOD_PATTERN_FAILURE`;

export const SAVE_CALORIE_INTAKE_INIT = `${PREFIX}SAVE_CALORIE_INTAKE_INIT`;
export const SAVE_CALORIE_INTAKE_SUCCESS = `${PREFIX}SAVE_CALORIE_INTAKE_SUCCESS`;
export const SAVE_CALORIE_INTAKE_FAILURE = `${PREFIX}SAVE_CALORIE_INTAKE_FAILURE`;

export const GET_NET_CALORIE_INTAKE_INIT = `${PREFIX}GET_NET_CALORIE_INTAKE_INIT`;
export const GET_NET_CALORIE_INTAKE_SUCCESS = `${PREFIX}GET_NET_CALORIE_INTAKE_SUCCESS`;
export const GET_NET_CALORIE_INTAKE_FAILURE = `${PREFIX}GET_NET_CALORIE_INTAKE_FAILURE`;

export const GET_DETECTED_FOOD_SUCCESS = `${PREFIX}GET_DETECTED_FOOD_SUCCESS`;
