export const PREFIX = "@@excPlan/";

export const GET_EXC_PATTERN_INIT = `${PREFIX}GET_EXC_PATTERN_INIT`;
export const GET_EXC_PATTERN_SUCCESS = `${PREFIX}GET_EXC_PATTERN_SUCCESS`;
export const GET_EXC_PATTERN_FAILURE = `${PREFIX}GET_EXC_PATTERN_FAILURE`;

export const POST_EXC_PATTERN_INIT = `${PREFIX}POST_EXC_PATTERN_INIT`;
export const POST_EXC_PATTERN_SUCCESS = `${PREFIX}POST_EXC_PATTERN_SUCCESS`;
export const POST_EXC_PATTERN_FAILURE = `${PREFIX}POST_EXC_PATTERN_FAILURE`;

export const POST_LEG_RESULTS_INIT = `${PREFIX}POST_LEG_RESULTS_INIT`;
export const POST_LEG_RESULT_SUCCESS = `${PREFIX}POST_LEG_RESULT_SUCCESS`;
export const POST_LEG_RESULT_FAILURE = `${PREFIX}POST_LEG_RESULT_FAILURE`;
