export const PREFIX = "@@profile/";

export const POST_RISK_FACTORS_INIT = `${PREFIX}POST_RISK_FACTORS_INIT`;
export const POST_RISK_FACTORS_SUCCESS = `${PREFIX}POST_RISK_FACTORS_SUCCESS`;
export const POST_RISK_FACTORS_FAILURE = `${PREFIX}POST_RISK_FACTORS_FAILURE`;
