export const PREFIX = "@@stressPlan/";

export const GET_STRESS_PLAN_INIT = `${PREFIX}GET_STRESS_PLAN_INIT`;
export const GET_STRESS_PLAN_SUCCESS = `${PREFIX}GET_STRESS_PLAN_SUCCESS`;
export const GET_STRESS_PLAN_FAILURE = `${PREFIX}GET_STRESS_PLAN_FAILURE`;

export const GET_DETECTED_FACE_SUCCESS = `${PREFIX}GET_DETECTED_FACE_SUCCESS`;
